name: Crookey CI
version: 1.0

trigger:
  branches:
    - main
    - develop
    - feature/*
  pull_requests:
    - main
    - develop

environments:
  - name: iOS Simulator
    runtime: iOS 17.0
    device: iPhone 15
  - name: macOS
    runtime: macOS 14.0

workflow:
  build:
    xcode_version: "15.4"
    scheme: "Crookey"
    destination: "platform=iOS Simulator,name=iPhone 15,OS=17.0"
    
    steps:
      - name: Install Dependencies
        run: |
          # Install any dependencies if needed
          echo "Installing dependencies..."
          
      - name: Build
        run: |
          xcodebuild build \
            -scheme Crookey \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" \
            -configuration Debug
            
      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme Crookey \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" \
            -configuration Debug \
            -enableCodeCoverage YES
            
  analyze:
    depends_on: build
    
    steps:
      - name: Static Analysis
        run: |
          xcodebuild analyze \
            -scheme Crookey \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0"
            
      - name: SwiftLint
        run: |
          if command -v swiftlint >/dev/null 2>&1; then
            swiftlint --reporter xcode
          else
            echo "SwiftLint not installed, skipping..."
          fi

artifacts:
  - type: build-logs
  - type: test-results
  - type: coverage-report